### ISSUE TITLE
Collapse previous section on selection of new section

### ISSUE THREAD

**Issue by sanket003** [LaurentiuUngur/LUExpandableTableView#1]
How to collapse previously expanded section on selection of new section?

**Comment by LaurentiuUngur** [comment]
You can't do that right now. There's no function to do that

**Comment by sanket003** [comment]
Any idea how to do it?

**Comment by LaurentiuUngur** [comment]
Uhm right know I would think to have a variable that keeps latest expanded section. When you expand a new one, the latest expanded has to collapse. Something like this should be the logic. In a future version I'll implement some functions that will expand/collapse a given section

**Comment by sanket003** [comment]
Okay. Thanks.

**Comment by LaurentiuUngur** [comment]
Thank you too
