### ISSUE TITLE
How to close open sections when other section is clicked 

### ISSUE THREAD

**Issue by kshit9** [LaurentiuUngur/LUExpandableTableView#11]

**Comment by LaurentiuUngur** [comment]
By using `collapseSections(at:)` function when the delegate `expandableTableView(: didSelectSectionHeader:)` it's called

**Comment by akashthakkar09** [comment]
Hello Im trying to pass collapseSections(at:) with below code self.tblSubCategory.expandSections(at: [section]) but still its not getting the single section open.

pls help me to provide to close all sections if any new section get open
