### ISSUE TITLE
Overlapping issue

### ISSUE THREAD

**Issue by xuanzi23** [LaurentiuUngur/LUExpandableTableView#12]
Hi, I facing this problem when I not using table view controller. It will appear like this
![simulator screen shot 21 aug 2017 10 07 32 am](https://user-images.githubusercontent.com/19340910/29501280-0600a288-865a-11e7-8fc9-d3e3077920f1.png)

How should I solve this?

**Comment by LaurentiuUngur** [comment]
This happens because height of the cells it's not correctly set.

**Comment by xuanzi23** [comment]
@LaurentiuUngur no matter using xib or storyboard right?

**Comment by LaurentiuUngur** [comment]
It shouldn't matter. Please check constraints.
