### ISSUE TITLE
Cannot use mutating member on immutable value: 'expandedSections' setter is inaccessible

### ISSUE THREAD

**Issue by iballan** [LaurentiuUngur/LUExpandableTableView#13]
I updated to latest version and got this errors : 
`/Pods/LUExpandableTableView/Sources/LUExpandableTableView.swift:277:13: Cannot use mutating member on immutable value: 'expandedSections' setter is inaccessible`
`
/Pods/LUExpandableTableView/Sources/LUExpandableTableView.swift:279:13: Cannot use mutating member on immutable value: 'expandedSections' setter is inaccessible
`

in this function:
```
    public func expandableSectionHeader(_ sectionHeader: LUExpandableTableViewSectionHeader, shouldExpandOrCollapseAtSection section: Int) {
        if expandedSections.contains(section) {
            expandedSections.remove(section) // <---------------- Here
        } else {
            expandedSections.insert(section)  // <---------------- and Here
        }
        
        beginUpdates()
        reloadSections(IndexSet(integer: section), with: animation)
        endUpdates()
        
        let sectionHeaderRect = rectForHeader(inSection: section)
        
        if !bounds.contains(sectionHeaderRect) {
            scrollRectToVisible(sectionHeaderRect, animated: true)
        }
    }
```

Swift 3.* , Xcode 9.0, iOS 11, LUExpandableTableView 3.0.0

**Comment by LaurentiuUngur** [comment]
That's because `expandedSections` has a private setter. Basically it's a read-only property.

**Comment by iballan** [comment]
The code i sent you was taken from **LUExpandableTableView.swift**, Is it that the library needs to be fixed ? @LaurentiuUngur

**Comment by LaurentiuUngur** [comment]
Version `3.0.0` supports just Swift 4.0+, that's why it doesn't work on Swift 3.0.
