### ISSUE TITLE
How to set cell and section height dynamically?

### ISSUE THREAD

**Issue by RajChanchal** [LaurentiuUngur/LUExpandableTableView#2]
As you have made the height related delegate methods non-optionals, how to set their heights dynamically? 
For a normal UITableView, we could use following methods:
```
tblView.rowHeight = UITableViewAutomaticDimension
tblView.sectionHeaderHeight = UITableViewAutomaticDimension
tblView.estimatedRowHeight = 44
```

**Comment by LaurentiuUngur** [comment]
You can return in delegate methods `UITableViewAutomaticDimension` instead of some value like 50.
