### ISSUE TITLE
Unavailability of "didDeSelectRowAt indexPath" function

### ISSUE THREAD

**Issue by tripathishivam35** [LaurentiuUngur/LUExpandableTableView#24]
I want to perform some operation of tableViewCells which requires Selection & Deselction of cells (like click on checkbox and uncheck it).
For that it requires didDeSelectRowAtIndexPath().
Could u add this delegate function or could you assist me on this?

**Comment by LaurentiuUngur** [comment]
<img width="833" alt="Screenshot 2019-03-12 at 20 39 51" src="https://user-images.githubusercontent.com/13499785/54226696-00adf980-4507-11e9-9011-74810ce48041.png">
There's already there. Please check example app for usage.
