### ISSUE TITLE
Flickering issues

### ISSUE THREAD

**Issue by PaulRBerg** [LaurentiuUngur/LUExpandableTableView#3]
Hello! Thanks firstly for this amazing library.

I have one problem with it. When I have pretty tall headers and cells, I encounter some really nasty flickering & weird repositions for the header. I uploaded a video [here](http://sendvid.com/nsei5ojk).

Any solution?

**Comment by LaurentiuUngur** [comment]
Hello ! I'm glad that you're using it.

Please set `estimatedRowHeight` and `estimatedSectionHeaderHeight` to a value that's appropriate to the heights of rows and headers. If I remember correctly, default one is 60 for both, but yours are taller.

**Comment by PaulRBerg** [comment]
Did just that, I set them at 196 before the video was recorded. It s not because of that.

I changed the row animation from fade to none. Maybe because of that?

**Comment by LaurentiuUngur** [comment]
You can try changing animation, even playing a little bit with that value to be more precisely with their real height. Also please check constraints, maybe you have some ambiguous constraints. What did you return in delegate methods for height ?

**Comment by PaulRBerg** [comment]
Pasted the methods here

```
func expandableTableView(_ expandableTableView: LUExpandableTableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        /// Returning `UITableViewAutomaticDimension` value on iOS 9 will cause reloading all cells due to an iOS 9 bug with automatic dimensions
        return 196
    }
    
    func expandableTableView(_ expandableTableView: LUExpandableTableView, heightForHeaderInSection section: Int) -> CGFloat {
        /// Returning `UITableViewAutomaticDimension` value on iOS 9 will cause reloading all cells due to an iOS 9 bug with automatic dimensions
        return 196
    }
```

Also, yes there was something strange happening with the constraints. I have a simple container view in the section's header xib and I was always getting the `UIViewAlertForUnsatisfiableConstraints` alert when the view was collapsing, so I simply changed the constraints from leading, top, bottom, trailing distance of 8 to `Less or equal 8`. Maybe it's because of this?

More info: The container view is the root view of the header, after the header's own root view of course.

**Comment by LaurentiuUngur** [comment]
For top, leading and trailing you can leave it equal to 8. For bottom put it also equal to 8 but change  priority to 750. Did the flicker occur even after resolving `UIViewAlertForUnsatisfiableConstraints` warning ?

**Comment by PaulRBerg** [comment]
Yes, it does unfortunately. With both my edited constraints + your priority 750 suggestion.

**Comment by LaurentiuUngur** [comment]
Try setting `estimatedRowHeight `and `estimatedSectionHeaderHeight` to 196 and return `UITableViewAutomaticDimension` in delegate methods. On which iOS version flicker occurs ? On both iOS 9 and 10 ?

**Comment by PaulRBerg** [comment]
It is worse. This is what happens now after I added `UITableViewAutomaticDimension ` and set the height before.

http://sendvid.com/zwqhcmkl

Happens on iOS 10. Didn't test on iOS 9 yet.

**Comment by PaulRBerg** [comment]
Any updates on this?

**Comment by LaurentiuUngur** [comment]
Sorry, but I don't have time to investigate until this weekend.

**Comment by LaurentiuUngur** [comment]
Sorry for the delay. I took a look at your problem, but I haven't found any solution and I don't have access to your source code.
