### ISSUE TITLE
Example Project doesn't run

### ISSUE THREAD

**Issue by RajChanchal** [LaurentiuUngur/LUExpandableTableView#4]
<img width="763" alt="screen shot 2017-02-13 at 9 28 10 am" src="https://cloud.githubusercontent.com/assets/7058465/22871938/e9a3ae3e-f1ce-11e6-8886-a0fc20accb71.png">

**Comment by LaurentiuUngur** [comment]
Please build first 
![screen shot 2017-02-14 at 09 03 36](https://cloud.githubusercontent.com/assets/13499785/22918774/8eaea896-f294-11e6-8a1b-7cb8eedcc4e8.png), then run the example app
