### ISSUE TITLE
Maybe simple problem

### ISSUE THREAD

**Issue by narekyan** [LaurentiuUngur/LUExpandableTableView#5]
How to expand section?
because when I click its not expanded
and cellforrow not called

**Comment by LaurentiuUngur** [comment]
Can you send me how you've used it ? I can't figure out why, if I don't see how you've used it

**Comment by narekyan** [comment]
Thanks
This is the swift file
In storyboard I just have standard Viewcontroller , Tableview and cell

[HistoryVC.swift.zip](https://github.com/LaurentiuUngur/LUExpandableTableView/files/799064/HistoryVC.swift.zip)

**Comment by LaurentiuUngur** [comment]
Sorry for the delay. I had a busy schedule. Please remove `LUExpandableTableViewSectionHeaderDelegate` from`class HistoryVC: BaseVC, LUExpandableTableViewDelegate,LUExpandableTableViewDataSource,LUExpandableTableViewSectionHeaderDelegate {`.
