### ISSUE TITLE
collapse the old header

### ISSUE THREAD

**Issue by keyhan76** [LaurentiuUngur/LUExpandableTableView#6]
Hi,
How should I collapse the previous cells when I expand a new one ?

**Comment by LaurentiuUngur** [comment]
IMHO no

**Comment by LaurentiuUngur** [comment]
Sorry, I haven't saw the `How`. Right now you cannot collapse/expand programatically

**Comment by LaurentiuUngur** [comment]
I've added the ability to expand/collapse sections programatically. Please see https://github.com/LaurentiuUngur/LUExpandableTableView/releases/tag/2.1.0
