### ISSUE TITLE
Cell Height

### ISSUE THREAD

**Issue by dx777** [LaurentiuUngur/LUExpandableTableView#8]
Hi, i have another tableview, inside cell that is expanded.
The problem is, when i expand header for the first time, its returning estimated row height, of the second tableview.
If i collapse it, then expand it one more time - everything workis fine.
So how can i make it works, for the first expand ?

```
    func expandableTableView(_ expandableTableView: LUExpandableTableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        if insideCell.unselectableTableView != nil {
            return insideCell.unselectableTableView.contentSize.height
            
        } else {
            return 55
        }
}
```
This whats returning on your Framework. This is what i have in tableview, that inside first cell 👍 

```
        unselectableTableView.estimatedRowHeight = 55
        unselectableTableView.rowHeight = UITableViewAutomaticDimension
```
  Please help, strugling for 3 days, tried different methods, including set all to UITableViewAutomaticDimension, didn't work.

Even found *workaround*, to expand and collapse header, in wievwillappear, but anyway animation is still visible for human eye.

**Comment by LaurentiuUngur** [comment]
Well you can try to calculate the height of each row since `UITableViewAutomaticDimension` won't work too good.

**Comment by dx777** [comment]
Thanks, i tried, it's not works good either.
Currently i reload table, in willDisplay cell method, it works fine, but footer of tableView, jumps up for a second, when i first expand section, here's a video :

https://www.dropbox.com/s/scu3kxlorgy0pzy/bug.mov?dl=0

**Comment by LaurentiuUngur** [comment]
Set a calculated value also for footer height/header height. Also try to set animations to none.
