### ISSUE TITLE
Centering header cell when tapped 

### ISSUE THREAD

**Issue by KevinAlexis** [LaurentiuUngur/LUExpandableTableView#9]
Hi!,well when i tap a headercell i reall need that tha section scrolls at top of expandableTableView  and expand its subviews 
I can barely archieve this by doing:
`self.mExpandableTV.scrollToRow(at: indexPath, at: .none, animated: true)`

but when the header scrolls at top it expands its subviews at the bottom of the list (i want it to show the firs t item), i cant find a way of solving this  
So? Is there a function that "center " the header tapped at top of tableView?

**Comment by LaurentiuUngur** [comment]
Hi ! I'm not 100% sure I've understood your issue, but I don't think so...just `scrollToRow()`
